# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "medo"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vladimir Yarotsky"]
  s.date = "2012-06-01"
  s.email = "vladimir.yarotksy@gmail.com"
  s.executables = ["medo"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README",
    "Rakefile",
    "VERSION",
    "bin/medo",
    "lib/medo.rb",
    "lib/medo/binary_task_reader.rb",
    "lib/medo/binary_task_writer.rb",
    "lib/medo/commands/clear.rb",
    "lib/medo/commands/delete.rb",
    "lib/medo/commands/done.rb",
    "lib/medo/commands/list.rb",
    "lib/medo/commands/new.rb",
    "lib/medo/commands/note.rb",
    "lib/medo/file_task_storage.rb",
    "lib/medo/numbering_text_task_writer.rb",
    "lib/medo/task.rb",
    "lib/medo/task_reader.rb",
    "lib/medo/task_writer.rb",
    "lib/medo/text_task_writer.rb",
    "medo.gemspec",
    "spec/integration_test.rb",
    "spec/lib/file_task_storage_spec.rb",
    "spec/lib/task_printer_spec.rb",
    "spec/lib/task_reader_spec.rb",
    "spec/lib/task_spec.rb",
    "spec/lib/text_task_printer_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/v-yarotsky/medo"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Simple CLI todo manager app"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gli>, [">= 2.0.0.rc3"])
      s.add_development_dependency(%q<minitest>, ["~> 3.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
    else
      s.add_dependency(%q<gli>, [">= 2.0.0.rc3"])
      s.add_dependency(%q<minitest>, ["~> 3.0"])
      s.add_dependency(%q<rake>, ["~> 0.9"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
    end
  else
    s.add_dependency(%q<gli>, [">= 2.0.0.rc3"])
    s.add_dependency(%q<minitest>, ["~> 3.0"])
    s.add_dependency(%q<rake>, ["~> 0.9"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
  end
end

